// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventService.proto

package org.wso2.grpc;

public final class EventServiceOuterClass {
  private EventServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventservice_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventservice_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022EventService.proto\022\014eventservice\032\033goog" +
      "le/protobuf/empty.proto\"\030\n\005Event\022\017\n\007payl" +
      "oad\030\001 \001(\t2\177\n\014EventService\0225\n\007process\022\023.e" +
      "ventservice.Event\032\023.eventservice.Event\"\000" +
      "\0228\n\007consume\022\023.eventservice.Event\032\026.googl" +
      "e.protobuf.Empty\"\000B\021\n\rorg.wso2.grpcP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_eventservice_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eventservice_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventservice_Event_descriptor,
        new String[] { "Payload", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
