// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: siddhi_MI_connect.proto

package io.siddhi.extension.io.grpc.util.service;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventservice.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string payload = 1;</code>
   */
  String getPayload();
  /**
   * <code>string payload = 1;</code>
   */
  com.google.protobuf.ByteString
      getPayloadBytes();
}
