// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: siddhi_MI_connect.proto

package io.siddhi.extension.io.grpc.util.service;

public interface SequenceCallRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:invokesequence.SequenceCallRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sequenceName = 1;</code>
   */
  String getSequenceName();
  /**
   * <code>string sequenceName = 1;</code>
   */
  com.google.protobuf.ByteString
      getSequenceNameBytes();

  /**
   * <pre>
   *json or xml
   * </pre>
   *
   * <code>string payloadAsJSON = 2;</code>
   */
  String getPayloadAsJSON();
  /**
   * <pre>
   *json or xml
   * </pre>
   *
   * <code>string payloadAsJSON = 2;</code>
   */
  com.google.protobuf.ByteString
      getPayloadAsJSONBytes();
}
