// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: siddhi_MI_connect.proto

package io.siddhi.extension.io.grpc.util.service;

public interface SequenceCallResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:invokesequence.SequenceCallResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseAsJSON = 1;</code>
   */
  String getResponseAsJSON();
  /**
   * <code>string responseAsJSON = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseAsJSONBytes();
}
