// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: siddhi_MI_connect.proto

package io.siddhi.extension.io.grpc.util.service;

public final class SiddhiMicroIntegratorProto {
  private SiddhiMicroIntegratorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_invokesequence_SequenceCallRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_invokesequence_SequenceCallRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_invokesequence_SequenceCallResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_invokesequence_SequenceCallResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_invokesequence_EmptyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_invokesequence_EmptyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027siddhi_MI_connect.proto\022\016invokesequenc" +
      "e\"B\n\023SequenceCallRequest\022\024\n\014sequenceName" +
      "\030\001 \001(\t\022\025\n\rpayloadAsJSON\030\002 \001(\t\".\n\024Sequenc" +
      "eCallResponse\022\026\n\016responseAsJSON\030\001 \001(\t\"\017\n" +
      "\rEmptyResponse2\336\001\n\016InvokeSequence\022g\n\030Cal" +
      "lSequenceWithResponse\022#.invokesequence.S" +
      "equenceCallRequest\032$.invokesequence.Sequ" +
      "enceCallResponse\"\000\022c\n\033CallSequenceWithou" +
      "tResponse\022#.invokesequence.SequenceCallR" +
      "equest\032\035.invokesequence.EmptyResponse\"\000B" +
      "A\n\033io.siddhi.extension.io.grpcB\032SiddhiMi" +
      "croIntegratorProtoP\001\242\002\003SMIb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_invokesequence_SequenceCallRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_invokesequence_SequenceCallRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_invokesequence_SequenceCallRequest_descriptor,
        new String[] { "SequenceName", "PayloadAsJSON", });
    internal_static_invokesequence_SequenceCallResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_invokesequence_SequenceCallResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_invokesequence_SequenceCallResponse_descriptor,
        new String[] { "ResponseAsJSON", });
    internal_static_invokesequence_EmptyResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_invokesequence_EmptyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_invokesequence_EmptyResponse_descriptor,
        new String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
