// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package package01.test;

public final class Sample {
  private Sample() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014sample.proto\032\033google/protobuf/empty.pr" +
      "oto\"\202\001\n\007Request\022\023\n\013stringValue\030\001 \001(\t\022\020\n\010" +
      "intValue\030\002 \001(\005\022\021\n\tlongValue\030\003 \001(\003\022\024\n\014boo" +
      "leanValue\030\004 \001(\010\022\022\n\nfloatValue\030\005 \001(\002\022\023\n\013d" +
      "oubleValue\030\006 \001(\001\"\203\001\n\010Response\022\023\n\013StringV" +
      "alue\030\001 \001(\t\022\020\n\010intValue\030\002 \001(\005\022\021\n\tLongValu" +
      "e\030\003 \001(\003\022\024\n\014booleanValue\030\004 \001(\010\022\022\n\nfloatVa" +
      "lue\030\005 \001(\002\022\023\n\013doubleValue\030\006 \001(\0012U\n\tMyServ" +
      "ice\022(\n\004send\022\010.Request\032\026.google.protobuf." +
      "Empty\022\036\n\007process\022\010.Request\032\t.ResponseB\022\n" +
      "\016package01.testP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new String[] { "StringValue", "IntValue", "LongValue", "BooleanValue", "FloatValue", "DoubleValue", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new String[] { "StringValue", "IntValue", "LongValue", "BooleanValue", "FloatValue", "DoubleValue", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
